name: Full Training Pipeline

on:
  workflow_dispatch:
    inputs:
      run_data_pipeline:
        description: 'Run Data Pipeline (ETL) ?'
        required: true
        default: true
        type: boolean
      run_model_pipeline:
        description: 'Run Model Training Pipeline ?'
        required: true
        default: true
        type: boolean

jobs:
  data-model-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
         pip install --upgrade pip
         pip install -r requirements/requirements_utils.txt
         pip install -r requirements/requirements_data.txt
         pip install -r requirements/requirements_model.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Data Pipeline
        if: ${{ inputs.run_data_pipeline == true }}
        run: python3 -m src.data.data_pipeline
        env:
            BUCKET_NAME: ${{ vars.BUCKET_NAME }}

      - name: Run Model Training
        if: ${{ inputs.run_model_pipeline == true }}
        run: python3 -m src.model.model_pipeline
        env:
            BUCKET_NAME: ${{ vars.BUCKET_NAME }}
